starting 2 processes for FSDP training
setting RLIMIT_NOFILE soft limit to 1048576 from 1048576
0 initializing distributed
1 initializing distributed
Creating trainer on process 1 with world size 2
Loaded model on rank 1
Error executing job with overrides: ['loss=ipo', 'model=pythia1-4b', 'datasets=[shp]', 'exp_name=pythia1-4b_ipo', 'mode=train', '++cache_dir=/home/jovyan/share/LLMAgent/zy/data', '++model.load_from=pythia1-4b_sft/LATEST/policy.pt']
Traceback (most recent call last):
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/cli/cli.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/cli/cli.py", line 291, in service
    server.serve()
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 139, in serve
    self._inform_used_ports(grpc_port=grpc_port, sock_port=sock_port)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 67, in _inform_used_ports
    pf.write(self._port_fname)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/service/port_file.py", line 26, in write
    f = tempfile.NamedTemporaryFile(prefix=bname, dir=dname, mode="w", delete=False)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpawv_65r4/port-1024449.txtah7ifain'
Traceback (most recent call last):
  File "/home/jovyan/notebook/zhouyang/HALOs/train.py", line 228, in main
    mp.spawn(worker_main, nprocs=world_size, args=(world_size, config, tokenizer, train_iterator, eval_iterator, policy, reference_model), join=True)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/jovyan/notebook/zhouyang/HALOs/train.py", line 62, in worker_main
    wandb.init(
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1169, in init
    raise e
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1146, in init
    wi.setup(kwargs)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 172, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 145, in __init__
    self._service.start()
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    _sentry.reraise(e)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/home/jovyan/share/LLMAgent/zy/HALOs/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.